using GPWebApi.DTO;
using Wallet.Interfaces;
using Wallet.Models;

namespace Wallet.Helper
{
	public class CustomerMapperHelper : ICustomerMapperHelper
	{
		private readonly IConfiguration _configuration;

		public CustomerMapperHelper(IConfiguration configuration)
		{
			_configuration = configuration;
		}
		public CustomerUpdateRequest MapCustomerDataToUpdateRequest(CustomerGetData data)
		{
			return new CustomerUpdateRequest
			{
				CustomerId = data.CustomerId,
				CustomerTypeId = data.CustomerTypeId,
				CustomerName = data.CustomerName,
				CustomerNamePrefix = data.CustomerNamePrefix,
				FirstName = data.CustomerFirstName,
				MiddleName = data.CustomerMiddleName,
				LastName = data.CustomerLastName,
				CustomerNameSuffix = data.CustomerNameSuffix,
				GlobalCustomerName = data.GlobalCustomerName,
				GlobalFirstName = data.GlobalCustomerFirstName,
				GlobalMiddleName = data.GlobalCustomerMiddleName,
				GlobalLastName = data.GlobalCustomerLastName,
				ContactName = data.ContactName,
				MailingAddressLine1 = data.MailingAddressLine1,
				MailingAddressLine2 = data.MailingAddressLine2,
				MailingDepartment = data.MailingDepartment,
				MailingSubDepartment = data.MailingSubDepartment,
				MailingStreetName = data.MailingStreetName,
				MailingBuildingNumber = data.MailingBuildingNumber,
				MailingBuildingName = data.MailingBuildingName,
				MailingFloor = data.MailingFloor,
				MailingPostBox = data.MailingPostBox,
				MailingRoom = data.MailingRoom,
				MailingCity = data.MailingCity,
				MailingTownLocationName = data.MailingTownLocationName,
				MailingDistrictName = data.MailingDistrictName,
				MailingStateOrProvince = data.MailingStateOrProvince,
				MailingPostalCode = data.MailingPostalCode,
				GlobalAddressLine1 = data.GlobalAddressLine1,
				GlobalAddressLine2 = data.GlobalAddressLine2,
				GlobalDepartment = data.GlobalDepartment,
				GlobalSubDepartment = data.GlobalSubDepartment,
				GlobalStreetName = data.GlobalStreetName,
				GlobalBuildingNumber = data.GlobalBuildingNumber,
				GlobalBuildingName = data.GlobalBuildingName,
				GlobalFloor = data.GlobalFloor,
				GlobalPostBox = data.GlobalPostBox,
				GlobalRoom = data.GlobalRoom,
				GlobalCity = data.GlobalCity,
				GlobalTownLocationName = data.GlobalTownLocationName,
				GlobalDistrictName = data.GlobalDistrictName,
				GlobalStateOrProvince = data.GlobalStateOrProvince,
				GlobalPostalCode = data.GlobalPostalCode,
				CountryCode = data.CountryCode,
				Phone = data.Phone,
				CellPhone = data.CellPhone,
				SMS = data.SMS,
				Fax = data.Fax,
				WKYCId = data.WKYCId,
				WKYCLevel = data.WKYCLevel,
				Email = data.Email,
				BranchId = data.BranchId,
				AccountNumber = data.AccountNumber,
				TaxId = data.TaxId,
				OccupationTypeId = data.OccupationTypeId,
				OccupationDescription = data.OccupationDescription,
				DateOfBirth = data.DateOfBirth,
				CityOfBirth = data.CityOfBirth,
				CountryOfBirthCode = data.CountryOfBirthCode,
				IdentificationTypeId = data.IdentificationTypeId,
				IdentificationNumber = data.IdentificationNumber,
				IdentificationIssuer = data.IdentificationIssuer,
				IdentificationCountryCode = data.IdentificationCountryCode,
				IdentificationExpirationDate = data.IdentificationExpirationDate,
				CompanyName = data.CompanyName,
				CompanyRegistrationNumber = data.CompanyRegistrationNumber,
				CompanyRegistrationCountryCode = data.CompanyRegistrationCountryCode,
				JobTitle = data.JobTitle,
				Department = data.Department,
				ExternalReference = data.ExternalReference,
				LegalEntityIdentification = data.LegalEntityIdentification,
				BusinessStructureTypeCode = data.BusinessStructureTypeCode,
				WholesaleOrRetail = data.WholesaleOrRetail,
				AvoxId = data.AvoxId,
				AMLRisk = data.AMLRisk,
				ABN = data.ABN,
				ACN = data.ACN,
				ARBN = data.ARBN,
				IsEnabled = data.IsEnabled,
				IsBank = data.IsBank,
				IsBusinessAccount = data.IsBusinessAccount,
				IsAutoCoverEnabled = data.IsAutoCoverEnabled,
				IsDualControlEnabled = data.IsDualControlEnabled,
				IsPaymentEnabled = data.IsPaymentEnabled,
				IsFXTradingEnabled = data.IsFXTradingEnabled,
				IsCurrencyCalculatorEnabled = data.IsCurrencyCalculatorEnabled,
				IsCashIn = data.IsCashIn,
				IsCashOut = data.IsCashOut,
				IsWKYCVerifier = data.IsWKYCVerifier,
				AllowThirdPartyPayments = data.AllowThirdPartyPayments,
				IsCharity = data.IsCharity,
				WebsiteUrl = data.WebsiteURL,
				Nationality = data.Nationality,
				GenderTypeId = (short)data.GenderTypeId,
				IsUSPerson = data.IsUSPerson,
				ReferredByPlatform = data.ReferredByPlatform,
				ReferredByName = data.ReferredByName,
				ElectronicDataSource = data.ElectronicDataSource,
				TraderNotes = data.TraderNotes,
				Memo = data.Memo,
				BusinessActivity = data.BusinessActivity,
				BaseCurrencyCode = data.BaseCurrencyCode,
				LimitCurrencyCode = data.LimitCurrencyCode,
				FXDealLimit = data.FXDealLimit,
				FXContractLimit = data.FXContractLimit,
				MarginPercent = data.MarginPercent,
				MarginCallPercent = data.MarginCallPercent,
				FXDealTypeTemplateId = data.FXDealTypeTemplateId.HasValue ? data.FXDealTypeTemplateId.Value : Guid.Empty,
				SettlementTypeTemplateId = data.SettlementTypeTemplateId.HasValue ? data.SettlementTypeTemplateId.Value : Guid.Empty,
				FeeTemplateId = data.FeeTemplateId.HasValue ? data.FeeTemplateId.Value : Guid.Empty,
				CurrencyPairAccessTemplateId = data.CurrencyPairAccessTemplateId.HasValue ? data.CurrencyPairAccessTemplateId.Value : Guid.Empty,
				CashSpreadTemplateId = data.CashSpreadTemplateId.HasValue ? data.CashSpreadTemplateId.Value : Guid.Empty,
				TomsSpreadTemplateId = data.TomsSpreadTemplateId.HasValue ? data.TomsSpreadTemplateId.Value : Guid.Empty,
				SpotSpreadTemplateId = data.SpotSpreadTemplateId.HasValue ? data.SpotSpreadTemplateId.Value : Guid.Empty,
				ForwardOutrightSpreadTemplateId = data.ForwardOutrightSpreadTemplateId.HasValue ? data.ForwardOutrightSpreadTemplateId.Value : Guid.Empty,
				ForwardWindowSpreadTemplateId = data.ForwardWindowSpreadTemplateId.HasValue ? data.ForwardWindowSpreadTemplateId.Value : Guid.Empty,
				CashCoverRateSpreadTemplateId = data.CashCoverRateSpreadTemplateId.HasValue ? data.CashCoverRateSpreadTemplateId.Value : Guid.Empty,
				TomsCoverRateSpreadTemplateId = data.TomsCoverRateSpreadTemplateId.HasValue ? data.TomsCoverRateSpreadTemplateId.Value : Guid.Empty,
				SpotCoverRateSpreadTemplateId = data.SpotCoverRateSpreadTemplateId.HasValue ? data.SpotCoverRateSpreadTemplateId.Value : Guid.Empty,
				ForwardOutrightCoverRateSpreadTemplateId = data.ForwardOutrightCoverRateSpreadTemplateId.HasValue ? data.ForwardOutrightCoverRateSpreadTemplateId.Value : Guid.Empty,
				ForwardWindowCoverRateSpreadTemplateId = data.ForwardWindowCoverRateSpreadTemplateId.HasValue ? data.ForwardWindowCoverRateSpreadTemplateId.Value : Guid.Empty,
				IncomingPaymentSpreadTemplateId = data.IncomingPaymentSpreadTemplateId.HasValue ? data.IncomingPaymentSpreadTemplateId.Value : Guid.Empty,
				IncomingPaymentCoverRateSpreadTemplateId = data.IncomingPaymentCoverRateSpreadTemplateId.HasValue ? data.IncomingPaymentCoverRateSpreadTemplateId.Value : Guid.Empty,
				MaximumContractLengthDays = data.MaximumContractLengthDays,
				MaximumForwardDays = data.MaximumForwardDays,
				InterestRate = data.InterestRate,
				MaxOverdraftAmountPerCurrency = data.MaxOverdraftAmountPerCurrency,
				MaxAggregateOverdraftAmount = data.MaxAggregateOverdraftAmount,
				OnQuoteFXDealEmailNotify = data.OnQuoteFXDealEmailNotify,
				OnQuoteFXDealEmailNotifyBcc = data.OnQuoteFXDealEmailNotifyBcc,
				OnBookFXDealEmailNotify = data.OnBookFXDealEmailNotify,
				OnBookFXDealEmailNotifyBcc = data.OnBookFXDealEmailNotifyBcc,
				OnPostIncomingWireEmailNotify = data.OnPostIncomingWireEmailNotify,
				OnPostIncomingWireEmailNotifyBcc = data.OnPostIncomingWireEmailNotifyBcc,
				WhiteLabelProfileId = data.WhiteLabelProfileId,
				AccountRepresentativeId = data.AccountRepresentativeId.HasValue ? data.AccountRepresentativeId.Value : Guid.Empty,
				//ReferrerId = data.ReferrerId is notnull || data.ReferrerId.Equals("null")? ,
			};
		}

		public CustomerCreateFromTemplateRequest MapSignUpDataToCustomerCreateFromTemplateRequest(string firstName, string lastName, string referredByName, string branchId, string referredByPlatform)
		{
			return new CustomerCreateFromTemplateRequest
			{
				BranchId = (string.IsNullOrEmpty(branchId)) ? null : new Guid(branchId),
				AccountRepresentativeId = new Guid(_configuration.GetValue<string>("Win:Beta:AccountRepresentativeId") ?? string.Empty),
				CustomerTemplateId = new Guid(_configuration.GetValue<string>("Win:Beta:CustomerTemplateId") ?? string.Empty),
				CustomerTypeId = 1,
				CustomerName = string.Empty,
				CustomerNamePrefix = string.Empty,
				FirstName = firstName,
				MiddleName = string.Empty,
				LastName = lastName,
				CustomerNameSuffix = string.Empty,
				GlobalCustomerName = string.Empty,
				GlobalFirstName = string.Empty,
				GlobalMiddleName = string.Empty,
				GlobalLastName = string.Empty,
				CountryCode = string.Empty,
				MailingAddressLine1 = string.Empty,
				MailingAddressLine2 = string.Empty,
				MailingDepartment = string.Empty,
				MailingSubDepartment = string.Empty,
				MailingStreetName = string.Empty,
				MailingBuildingNumber = string.Empty,
				MailingBuildingName = string.Empty,
				MailingFloor = string.Empty,
				MailingPostBox = string.Empty,
				MailingRoom = string.Empty,
				MailingCity = string.Empty,
				MailingTownLocationName = string.Empty,
				MailingDistrictName = string.Empty,
				MailingStateOrProvince = string.Empty,
				MailingPostalCode = string.Empty,
				Phone = string.Empty,
				Fax = string.Empty,
				WKYCId = string.Empty,
				TaxId = string.Empty,
				AccountNumber = string.Empty,
				ReferredByPlatform = referredByPlatform,
				ReferredByName = referredByName,
			};
		}

		public CustomerCreateFromTemplateRequest MapSignUpDataToCustomerCreateFromTemplateRequest(string firstName, string lastName, string email, string cellphone, string referredByName, string branchId, string notaryNodeCountryCode, string referredByPlatform)
		{
			return new CustomerCreateFromTemplateRequest
			{
				BranchId = (string.IsNullOrEmpty(branchId)) ? null : new Guid(branchId),
				AccountRepresentativeId = new Guid(_configuration.GetValue<string>("Win:Beta:AccountRepresentativeId") ?? string.Empty),
				CustomerTemplateId = new Guid(_configuration.GetValue<string>("Win:Beta:CustomerTemplateId") ?? string.Empty),
				CustomerTypeId = 1,
				CustomerName = string.Empty,
				CustomerNamePrefix = string.Empty,
				FirstName = firstName,
				MiddleName = string.Empty,
				LastName = lastName,
				CustomerNameSuffix = string.Empty,
				GlobalCustomerName = string.Empty,
				GlobalFirstName = string.Empty,
				GlobalMiddleName = string.Empty,
				GlobalLastName = string.Empty,
				CountryCode = !string.IsNullOrEmpty(notaryNodeCountryCode) ? notaryNodeCountryCode : _configuration.GetValue<string>("Win:Beta:DefaultCountryCode") ?? string.Empty,
				MailingAddressLine1 = string.Empty,
				MailingAddressLine2 = string.Empty,
				MailingDepartment = string.Empty,
				MailingSubDepartment = string.Empty,
				MailingStreetName = string.Empty,
				MailingBuildingNumber = string.Empty,
				MailingBuildingName = string.Empty,
				MailingFloor = string.Empty,
				MailingPostBox = string.Empty,
				MailingRoom = string.Empty,
				MailingCity = string.Empty,
				MailingTownLocationName = string.Empty,
				MailingDistrictName = string.Empty,
				MailingStateOrProvince = string.Empty,
				MailingPostalCode = string.Empty,
				Email = email,
				Phone = string.Empty,
				CellPhone = cellphone,
				Fax = string.Empty,
				WKYCId = string.Empty,
				TaxId = string.Empty,
				AccountNumber = string.Empty,
				ReferredByPlatform = referredByPlatform,
				ReferredByName = referredByName,
			};
		}

		public CustomerCreateFromTemplateRequest MapSignUpDataToCustomerCreateFromTemplateRequest(string firstName, string lastName, string email, string cellphone, string referredByName, string branchId, string referredByPlatform)
		{
			return new CustomerCreateFromTemplateRequest
			{
				BranchId = (string.IsNullOrEmpty(branchId)) ? null : new Guid(branchId),
				AccountRepresentativeId = new Guid(_configuration.GetValue<string>("Win:Beta:AccountRepresentativeId") ?? string.Empty),
				CustomerTemplateId = new Guid(_configuration.GetValue<string>("Win:Beta:CustomerTemplateId") ?? string.Empty),
				CustomerTypeId = 1,
				CustomerName = string.Empty,
				CustomerNamePrefix = string.Empty,
				FirstName = firstName,
				MiddleName = string.Empty,
				LastName = lastName,
				CustomerNameSuffix = string.Empty,
				GlobalCustomerName = string.Empty,
				GlobalFirstName = string.Empty,
				GlobalMiddleName = string.Empty,
				GlobalLastName = string.Empty,
				CountryCode = _configuration.GetValue<string>("Win:Beta:DefaultCountryCode") ?? string.Empty,
				MailingAddressLine1 = string.Empty,
				MailingAddressLine2 = string.Empty,
				MailingDepartment = string.Empty,
				MailingSubDepartment = string.Empty,
				MailingStreetName = string.Empty,
				MailingBuildingNumber = string.Empty,
				MailingBuildingName = string.Empty,
				MailingFloor = string.Empty,
				MailingPostBox = string.Empty,
				MailingRoom = string.Empty,
				MailingCity = string.Empty,
				MailingTownLocationName = string.Empty,
				MailingDistrictName = string.Empty,
				MailingStateOrProvince = string.Empty,
				MailingPostalCode = string.Empty,
				Email = email,
				Phone = string.Empty,
				CellPhone = cellphone,
				Fax = string.Empty,
				WKYCId = string.Empty,
				TaxId = string.Empty,
				AccountNumber = string.Empty,
				ReferredByPlatform = referredByPlatform,
				ReferredByName = referredByName,
			};
		}

		public CustomerCreateFromTemplateRequest MapUserSignUpModelToCustomerCreateFromTemplateRequest(UserSignUpModel model)
		{
			return new CustomerCreateFromTemplateRequest
			{
				BranchId = null,
				AccountRepresentativeId = new Guid(_configuration.GetValue<string>("Win:Beta:AccountRepresentativeId") ?? string.Empty),
				CustomerTemplateId = new Guid(_configuration.GetValue<string>("Win:Beta:CustomerTemplateId") ?? string.Empty),
				CustomerTypeId = 1,
				CustomerName = string.Empty,
				CustomerNamePrefix = string.Empty,
				FirstName = model.FirstName,
				MiddleName = string.Empty,
				LastName = model.LastName,
				CustomerNameSuffix = string.Empty,
				GlobalCustomerName = string.Empty,
				GlobalFirstName = string.Empty,
				GlobalMiddleName = string.Empty,
				GlobalLastName = string.Empty,
				CountryCode = string.Empty,
				MailingAddressLine1 = string.Empty,
				MailingAddressLine2 = string.Empty,
				MailingDepartment = string.Empty,
				MailingSubDepartment = string.Empty,
				MailingStreetName = string.Empty,
				MailingBuildingNumber = string.Empty,
				MailingBuildingName = string.Empty,
				MailingFloor = string.Empty,
				MailingPostBox = string.Empty,
				MailingRoom = string.Empty,
				MailingCity = string.Empty,
				MailingTownLocationName = string.Empty,
				MailingDistrictName = string.Empty,
				MailingStateOrProvince = string.Empty,
				MailingPostalCode = string.Empty,
				Email = model.Email,
				Phone = string.Empty,
				CellPhone = string.Empty,
				Fax = string.Empty,
				WKYCId = string.Empty,
				TaxId = string.Empty,
				AccountNumber = string.Empty
			};
		}

		public CustomerAccountAliasCreateRequest MapNewCustomerAccountAliasToCustomerAccountAliasCreateRequest(NewCustomerAccountAlias model)
		{
			return new CustomerAccountAliasCreateRequest
			{
				CustomerId = model.CustomerId,
				AccountAlias = model.AccountAlias,
				AccountAliasType = model.AccountAliasType,
				SetAsDefault = model.SetAsDefault,
			};
		}
	}
}
